= Arquillian Containers

{% if book.currentVersion == "5.181" %}

WARNING: This feature is released in *_technical preview_*. It's fully usable and supported but it's subject to change in future versions. Read more in link:/general-info/technical-preview.adoc[Features in Technical Preview].

{% endif %}

The Payara Arquillian containers provide various Arquillian containers for integration testing with Payara.

In version {{ book.currentVersion }}, there are containers available for the following distributions:

* link:payara-micro-managed.adoc[Payara Micro Managed]
* link:payara-server-remote.adoc[Payara Server Remote]
* link:payara-server-managed.adoc[Payara Server Managed]
* link:payara-server-embedded.adoc[Payara Server Embedded]

=== Obtaining the Containers

Arquillian containers are included in a project via their Maven coordinates:

[source,XML]
----
<dependency>
    <groupId>fish.payara.arquillian</groupId>
    <artifactId>arquillian-payara-${container-name}</artifactId>
    <version>${version}</version>
</dependency>
----